# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m8iJheO1WQYBJeiw1zgdJC5KtFQhzY_e
"""

# Define the SARIMA model order
order = (0, 1, 1)
seasonal_order = (0, 1, 1, 12) # (P, D, Q, S) for seasonal part

# Fit the SARIMA model
# Using enforce_stationarity=False and enforce_invertibility=False
# can sometimes help with convergence for certain datasets, though often not needed.
model = SARIMAX(y,
                order=order,
                seasonal_order=seasonal_order,
                enforce_stationarity=False,
                enforce_invertibility=False)

results = model.fit()

# Display the model summary
print(results.summary())

import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.statespace.sarimax import SARIMAX
import warnings

warnings.filterwarnings("ignore")

# Load the AirPassengers dataset
# This dataset is often available directly or can be simulated/downloaded
# For demonstration, let's create a placeholder or load from statsmodels if available
try:
    from statsmodels.datasets import airquality # This isn't AirPassengers, but for a quick demo if AirPassengers isn't direct
    data = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/AirPassengers.csv')
    data.columns = ['Month', 'Passengers']
    data['Month'] = pd.to_datetime(data['Month'], format='%Y-%m')
    data = data.set_index('Month')
    y = data['Passengers']
    print("AirPassengers dataset loaded successfully.")
except Exception as e:
    print(f"Could not load AirPassengers directly, trying alternative method or creating dummy data: {e}")
    # Fallback to dummy data if loading fails
    dates = pd.date_range(start='1949-01-01', periods=144, freq='MS')
    # Simple trend and seasonality for demonstration
    passengers = [100 + i*2 + 50*abs(pd.Timestamp(date).month - 6)/6 + 20* (pd.Timestamp(date).year - 1949) for i, date in enumerate(dates)]
    y = pd.Series(passengers, index=dates)
    print("Generated dummy time series data.")

# Display the first few rows and plot the data
print(y.head())
y.plot(figsize=(12, 6))
plt.title('Air Passengers Data (or Dummy Series)')
plt.xlabel('Date')
plt.ylabel('Number of Passengers')
plt.grid(True)
plt.show()



"""Now, let's fit the SARIMA model with the specified order `(0,1,1)(0,1,1)12`."""